name: Build LaTeX Document

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup TeX Live
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main_en.tex
        latexmk_use_xelatex: true
          
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: latex-pdf-${{ github.sha }}
        path: main_en.pdf
        retention-days: 30